apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
      default: "https://github.com/Costas1992/ci-cd-final-project.git"
    - name: branch
      type: string
      default: "main"
    - name: build-image
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/sn-labs-kostahobby/counter:latest"
    - name: app-name
      type: string
      default: "counter"
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: flake8
      taskRef:
        name: flake8
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: output

    - name: nose
      taskRef:
        name: nose
      runAfter:
        - flake8
      workspaces:
        - name: source
          workspace: output

    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - nose
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: $(params.build-image)

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-image
      workspaces:
        - name: manifest-dir
          workspace: output
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
